g_common_field_no_needed = [
    # 基本模型
    'model',
    'info',
    'field_id',
    'inherited_model_ids',
    'access_ids',
    'rule_ids',
    'transient',
    'modules',
    'view_ids',
    'count',
    'is_mail_thread',
    'id',
    'create_uid',
    # 'create_date',
    'write_uid',
    'write_date',
    # 邮箱
    'message_is_follower',
    'message_follower_ids',
    'message_partner_ids',
    'message_channel_ids',
    'message_ids',
    'message_unread',
    'message_unread_counter',
    'message_needaction',
    'message_needaction_counter',
    'message_has_error',
    'message_has_error_counter',
    'message_attachment_count',
    'message_main_attachment_id',
    'website_message_ids',
    'id',
    'display_name',
    # 邮箱混合
    'activity_ids',
    'activity_state',
    'activity_user_id',
    'activity_type_id',
    'activity_date_deadline',
    'activity_summary',
    'id',
    'display_name',
    '__last_update',

    #其它
    'dynamic_fields_show',
    'move_id',
]